server:
  port: 18080
  servlet:
    context-path: /employee

thread-pool: 10
email: aaa@abc.com


logging:
  level:
    #ROOT: DEBUG
    #org.springframework.web: DEBUG
    #guru.springframework.controllers: DEBUG
    #org.hibernate: DEBUG
    org.springframework.cache: TRACE
